### ISSUE TITLE
Update package metadata with both licenses (this project MIT and GCC GPL)

### ISSUE THREAD

**Issue by carlosperate** [carlosperate/arm-none-eabi-gcc-py-package#10]
- https://packaging.python.org/en/latest/specifications/core-metadata/#license-expression
- https://packaging.python.org/en/latest/specifications/core-metadata/#license-expression
- https://spdx.org/licenses/GPL-3.0-only.html

Should probably also add a `LICENSE-GCC` file.
```toml
[project]
license = "MIT AND GPL-3.0-only"
license-files = ["LICENSE*"]
```
